+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Tue Dec  6 08:12:30 2022 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL ImageMagick
+ pkgs=ImageMagick
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs ImageMagick --node 1 --tempfile ''
+ tmpfile2='Error: 
 Problem: package ImageMagick-6.9.12.40-1.an8.riscv64 requires libMagickCore-6.Q16.so.7()(64bit), but none of the providers can be installed
  - package ImageMagick-6.9.12.40-1.an8.riscv64 requires libMagickWand-6.Q16.so.7()(64bit), but none of the providers can be installed
  - package ImageMagick-6.9.12.40-1.an8.riscv64 requires ImageMagick-libs(riscv-64) = 6.9.12.40-1.an8, but none of the providers can be installed
  - conflicting requests
  - nothing provides libIlmImf-2_3.so.24()(64bit) needed by ImageMagick-libs-6.9.12.40-1.an8.riscv64'
+ '[' -z '' ']'
+ tmpfile='Error: 
 Problem: package ImageMagick-6.9.12.40-1.an8.riscv64 requires libMagickCore-6.Q16.so.7()(64bit), but none of the providers can be installed
  - package ImageMagick-6.9.12.40-1.an8.riscv64 requires libMagickWand-6.Q16.so.7()(64bit), but none of the providers can be installed
  - package ImageMagick-6.9.12.40-1.an8.riscv64 requires ImageMagick-libs(riscv-64) = 6.9.12.40-1.an8, but none of the providers can be installed
  - conflicting requests
  - nothing provides libIlmImf-2_3.so.24()(64bit) needed by ImageMagick-libs-6.9.12.40-1.an8.riscv64'
+ cp -r ../common ./tmp
+ cd ./tmp
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Tue Dec  6 08:13:01 2022 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Dec  6 08:13:02 2022 - INFO  - Start to run test.
+ convert -resize 900x600 -quality 70 -strip test3.jpg thumbnail.jpg
oe_test_ImageMagick_02.sh: line 28: convert: command not found
++ identify -verbose thumbnail.jpg
++ grep Quality
oe_test_ImageMagick_02.sh: line 29: identify: command not found
++ grep -cE 70
+ CHECK_RESULT 0 1
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ImageMagick_02.sh line 29'
+ message='oe_test_ImageMagick_02.sh line 29'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ImageMagick_02.sh line 29'
Tue Dec  6 08:13:03 2022 - ERROR - oe_test_ImageMagick_02.sh line 29
+ return 0
+ convert -resize 900x600 -quality 100 -strip test3.jpg thumbnail1.jpg
oe_test_ImageMagick_02.sh: line 30: convert: command not found
++ identify -verbose thumbnail1.jpg
++ grep Quality
++ grep -cE 100
oe_test_ImageMagick_02.sh: line 31: identify: command not found
+ CHECK_RESULT 0 1
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ImageMagick_02.sh line 31'
+ message='oe_test_ImageMagick_02.sh line 31'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ImageMagick_02.sh line 31'
Tue Dec  6 08:13:03 2022 - ERROR - oe_test_ImageMagick_02.sh line 31
+ return 0
+ convert -resize 900x600 -quality 101 -strip test3.jpg thumbnail2.jpg
oe_test_ImageMagick_02.sh: line 32: convert: command not found
++ identify -verbose thumbnail2.jpg
++ grep Quality
++ grep -cE 100
oe_test_ImageMagick_02.sh: line 33: identify: command not found
+ CHECK_RESULT 0 1
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ImageMagick_02.sh line 33'
+ message='oe_test_ImageMagick_02.sh line 33'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ImageMagick_02.sh line 33'
Tue Dec  6 08:13:04 2022 - ERROR - oe_test_ImageMagick_02.sh line 33
+ return 0
+ convert -resize 900x600 -quality -1 -strip test3.jpg thumbnail3.jpg
oe_test_ImageMagick_02.sh: line 34: convert: command not found
++ identify -verbose thumbnail3.jpg
oe_test_ImageMagick_02.sh: line 35: identify: command not found
++ grep Quality
++ grep -cE 100
+ CHECK_RESULT 0 1
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ImageMagick_02.sh line 35'
+ message='oe_test_ImageMagick_02.sh line 35'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ImageMagick_02.sh line 35'
Tue Dec  6 08:13:05 2022 - ERROR - oe_test_ImageMagick_02.sh line 35
+ return 0
+ convert -resize '150x100!' test1.jpg suof1.jpg
oe_test_ImageMagick_02.sh: line 36: convert: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ImageMagick_02.sh line 37'
+ message='oe_test_ImageMagick_02.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ImageMagick_02.sh line 37'
Tue Dec  6 08:13:06 2022 - ERROR - oe_test_ImageMagick_02.sh line 37
+ return 0
+ test -f suof1.jpg
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ImageMagick_02.sh line 39'
+ message='oe_test_ImageMagick_02.sh line 39'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ImageMagick_02.sh line 39'
Tue Dec  6 08:13:06 2022 - ERROR - oe_test_ImageMagick_02.sh line 39
+ return 0
+ convert -resize '150x100>' test2.jpg suof2.jpg
oe_test_ImageMagick_02.sh: line 40: convert: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ImageMagick_02.sh line 41'
+ message='oe_test_ImageMagick_02.sh line 41'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ImageMagick_02.sh line 41'
Tue Dec  6 08:13:07 2022 - ERROR - oe_test_ImageMagick_02.sh line 41
+ return 0
+ test -f suof2.jpg
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ImageMagick_02.sh line 43'
+ message='oe_test_ImageMagick_02.sh line 43'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ImageMagick_02.sh line 43'
Tue Dec  6 08:13:08 2022 - ERROR - oe_test_ImageMagick_02.sh line 43
+ return 0
+ convert -resize '150x100<' test3.jpg suof3.jpg
oe_test_ImageMagick_02.sh: line 44: convert: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ImageMagick_02.sh line 45'
+ message='oe_test_ImageMagick_02.sh line 45'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ImageMagick_02.sh line 45'
Tue Dec  6 08:13:08 2022 - ERROR - oe_test_ImageMagick_02.sh line 45
+ return 0
+ test -f suof3.jpg
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ImageMagick_02.sh line 47'
+ message='oe_test_ImageMagick_02.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ImageMagick_02.sh line 47'
Tue Dec  6 08:13:09 2022 - ERROR - oe_test_ImageMagick_02.sh line 47
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Dec  6 08:13:10 2022 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 10
+ test 10 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Dec  6 08:13:10 2022 - ERROR - failed to execute the case.
+ exit 10
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Dec  6 08:13:11 2022 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z Error: 
 Problem: package ImageMagick-6.9.12.40-1.an8.riscv64 requires libMagickCore-6.Q16.so.7()(64bit), but none of the providers can be installed
  - package ImageMagick-6.9.12.40-1.an8.riscv64 requires libMagickWand-6.Q16.so.7()(64bit), but none of the providers can be installed
  - package ImageMagick-6.9.12.40-1.an8.riscv64 requires ImageMagick-libs(riscv-64) = 6.9.12.40-1.an8, but none of the providers can be installed
  - conflicting requests
  - nothing provides libIlmImf-2_3.so.24()(64bit) needed by ImageMagick-libs-6.9.12.40-1.an8.riscv64 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile 'Error: 
 Problem: package ImageMagick-6.9.12.40-1.an8.riscv64 requires libMagickCore-6.Q16.so.7()(64bit), but none of the providers can be installed
  - package ImageMagick-6.9.12.40-1.an8.riscv64 requires libMagickWand-6.Q16.so.7()(64bit), but none of the providers can be installed
  - package ImageMagick-6.9.12.40-1.an8.riscv64 requires ImageMagick-libs(riscv-64) = 6.9.12.40-1.an8, but none of the providers can be installed
  - conflicting requests
  - nothing provides libIlmImf-2_3.so.24()(64bit) needed by ImageMagick-libs-6.9.12.40-1.an8.riscv64'
Traceback (most recent call last):
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 181, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 152, in rpm_remove
    with open(tmpfile, "r") as f:
OSError: [Errno 36] File name too long: 'Error: \n Problem: package ImageMagick-6.9.12.40-1.an8.riscv64 requires libMagickCore-6.Q16.so.7()(64bit), but none of the providers can be installed\n  - package ImageMagick-6.9.12.40-1.an8.riscv64 requires libMagickWand-6.Q16.so.7()(64bit), but none of the providers can be installed\n  - package ImageMagick-6.9.12.40-1.an8.riscv64 requires ImageMagick-libs(riscv-64) = 6.9.12.40-1.an8, but none of the providers can be installed\n  - conflicting requests\n  - nothing provides libIlmImf-2_3.so.24()(64bit) needed by ImageMagick-libs-6.9.12.40-1.an8.riscv64'
+ '[' 0 -ne 0 ']'
+ rm -rf ../tmp
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Dec  6 08:13:15 2022 - INFO  - End to restore the test environment.
