+ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Thu Dec 22 22:59:25 2022 - INFO  - Start to prepare the test environment.
+ useradd Jevons
useradd: user 'Jevons' already exists
++ id -u Jevons
+ uid=1001
+ LOG_INFO 'End to prepare the environment'
+ message='End to prepare the environment'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the environment'
Thu Dec 22 22:59:26 2022 - INFO  - End to prepare the environment
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Thu Dec 22 22:59:28 2022 - INFO  - Start to run test.
+ service auditd restart
oe_test_audit_monitor_system_use.sh: line 31: service: command not found
+ auditctl -D
No rules
+ CHECK_RESULT 0 0 0 'clean failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='clean failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ auditctl -a always,exit -S all -F uid=1001 -k syscall
Error detecting machine type
+ CHECK_RESULT 255 0 0 'add rule failed'
+ actual_result=255
+ expect_result=0
+ mode=0
+ error_log='add rule failed'
+ '[' -z 255 ']'
+ '[' 0 -eq 0 ']'
+ test 255x '!=' 0x
+ test -n 'add rule failed'
+ LOG_ERROR 'add rule failed'
+ message='add rule failed'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'add rule failed'
Thu Dec 22 22:59:30 2022 - ERROR - add rule failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_monitor_system_use.sh line 35'
+ message='oe_test_audit_monitor_system_use.sh line 35'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_monitor_system_use.sh line 35'
Thu Dec 22 22:59:31 2022 - ERROR - oe_test_audit_monitor_system_use.sh line 35
+ return 0
+ auditctl -l
+ grep -e '-a always,exit -S all -F uid=1001'
+ CHECK_RESULT 1 0 0 'grep failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='grep failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'grep failed'
+ LOG_ERROR 'grep failed'
+ message='grep failed'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'grep failed'
Thu Dec 22 22:59:33 2022 - ERROR - grep failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_monitor_system_use.sh line 37'
+ message='oe_test_audit_monitor_system_use.sh line 37'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_monitor_system_use.sh line 37'
Thu Dec 22 22:59:34 2022 - ERROR - oe_test_audit_monitor_system_use.sh line 37
+ return 0
++ date +%T
+ starttime=22:59:34
+ su - Jevons -c pwd
/home/Jevons
+ CHECK_RESULT 0 0 0 'login failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='login failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
++ date +%T
+ endtime=22:59:40
+ ausearch -ts 22:59:34 -te 22:59:40 -k syscall
+ grep pwd
Thu Dec 22 23:29:19 2022 - ERROR - Timeout : Command 'bash -x oe_test_audit_monitor_system_use.sh' timed out after 1799.9973910120002 seconds
