+ source common/common_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Thu Dec 29 01:58:03 2022 - INFO  - Start to prepare the test environment.
+ get_disk
++ TEST_DISK
++ id=1
++ python3 /root/mugen-riscv/libs/locallibs/get_test_device.py --device disk --node 1
+ disks='vdb vdc vdd vde'
+ disk_list=($disks)
+ disk1=vdb
+ disk2=vdc
+ DNF_INSTALL ntfs-3g
+ pkgs=ntfs-3g
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs ntfs-3g --node 1 --tempfile ''
+ tmpfile2=/tmp/tmp9cezxutv
+ '[' -z '' ']'
+ tmpfile=/tmp/tmp9cezxutv
+ mkntfs --fast /dev/vdb
Cluster size has been automatically set to 4096 bytes.
Creating NTFS volume structures.
mkntfs completed successfully. Have a nice day.
+ mkntfs --fast /dev/vdc
Cluster size has been automatically set to 4096 bytes.
Creating NTFS volume structures.
mkntfs completed successfully. Have a nice day.
+ mkdir -p /mnt/windows
+ ntfs-3g /dev/vdb /mnt/windows
modprobe: ERROR: could not insert 'fuse': Exec format error
ntfs-3g-mount: fuse device is missing, try 'modprobe fuse' as root
+ mkdir /mnt/windows/test
+ touch test.txt /mnt/windows/test.txt /mnt/windows/test/a.txt
+ umount /mnt/windows
umount: /mnt/windows: not mounted.
+ LOG_INFO 'Finish preparing the test environment.'
+ message='Finish preparing the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish preparing the test environment.'
Thu Dec 29 01:58:36 2022 - INFO  - Finish preparing the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Thu Dec 29 01:58:37 2022 - INFO  - Start to run test.
+ ntfssecaudit --help
+ grep Usage:
Usage:
+ CHECK_RESULT 0 0 0 'Check ntfssecaudit --help failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check ntfssecaudit --help failed.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ ntfssecaudit --version
+ grep 'ntfssecaudit v'
ntfssecaudit v2021.8.22 (libntfs-3g) - Audit security data on a NTFS Volume.
+ CHECK_RESULT 0 0 0 'Check ntfssecaudit --version failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check ntfssecaudit --version failed.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ ntfssecaudit -t
+ grep 'No errors were found'
No errors were found
No errors were found
+ CHECK_RESULT 0 0 0 'Check ntfssecaudit -t failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check ntfssecaudit -t failed.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ ntfssecaudit -h test.txt
+ grep 'No errors were found'
No errors were found
No errors were found
+ CHECK_RESULT 0 0 0 'Check ntfssecaudit -h failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check ntfssecaudit -h failed.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ ntfssecaudit -arv /dev/vdb
+ grep 'No errors were found'
"/dev/vdb" opened read-only
"/dev/vdb" closed
No errors were found
No errors were found
+ CHECK_RESULT 0 0 0 'Check ntfssecaudit -arv failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check ntfssecaudit -arv failed.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ ntfssecaudit -v /dev/vdb test.txt
+ grep 'No errors were found'
"/dev/vdb" opened read-only
"/dev/vdb" closed
** 1 error was found
+ CHECK_RESULT 1 0 0 'Check ntfssecaudit -v failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfssecaudit -v failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfssecaudit -v failed.'
+ LOG_ERROR 'Check ntfssecaudit -v failed.'
+ message='Check ntfssecaudit -v failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ntfssecaudit -v failed.'
Thu Dec 29 01:58:49 2022 - ERROR - Check ntfssecaudit -v failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfssecaudit.sh line 46'
+ message='oe_test_ntfs-3g_ntfssecaudit.sh line 46'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfssecaudit.sh line 46'
Thu Dec 29 01:58:49 2022 - ERROR - oe_test_ntfs-3g_ntfssecaudit.sh line 46
+ return 0
+ ntfssecaudit -rv /dev/vdb test
+ grep 'No errors were found'
"/dev/vdb" opened read-only
"/dev/vdb" closed
** 1 error was found
+ CHECK_RESULT 1 0 0 'Check ntfssecaudit -rv failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfssecaudit -rv failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfssecaudit -rv failed.'
+ LOG_ERROR 'Check ntfssecaudit -rv failed.'
+ message='Check ntfssecaudit -rv failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ntfssecaudit -rv failed.'
Thu Dec 29 01:58:50 2022 - ERROR - Check ntfssecaudit -rv failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfssecaudit.sh line 48'
+ message='oe_test_ntfs-3g_ntfssecaudit.sh line 48'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfssecaudit.sh line 48'
Thu Dec 29 01:58:51 2022 - ERROR - oe_test_ntfs-3g_ntfssecaudit.sh line 48
+ return 0
+ ntfssecaudit -bv /dev/vdb test
+ grep 'No errors were found'
"/dev/vdb" opened read-only
"/dev/vdb" closed
** 1 error was found
+ CHECK_RESULT 1 0 0 'Check ntfssecaudit -bv failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfssecaudit -bv failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfssecaudit -bv failed.'
+ LOG_ERROR 'Check ntfssecaudit -bv failed.'
+ message='Check ntfssecaudit -bv failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ntfssecaudit -bv failed.'
Thu Dec 29 01:58:51 2022 - ERROR - Check ntfssecaudit -bv failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfssecaudit.sh line 50'
+ message='oe_test_ntfs-3g_ntfssecaudit.sh line 50'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfssecaudit.sh line 50'
Thu Dec 29 01:58:52 2022 - ERROR - oe_test_ntfs-3g_ntfssecaudit.sh line 50
+ return 0
+ ntfssecaudit -sev /dev/vdb test.txt
+ grep 'No errors were found'
"/dev/vdb" opened read-write
"/dev/vdb" closed
No errors were found
No errors were found
+ CHECK_RESULT 0 0 0 'Check ntfssecaudit -sev failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check ntfssecaudit -sev failed.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ ntfssecaudit /dev/vdb 777 test.txt
+ grep 'No errors were found'
"/dev/vdb" opened read-write
"/dev/vdb" closed
** 1 error was found
+ CHECK_RESULT 1 0 0 'Check ntfssecaudit perms file failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfssecaudit perms file failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfssecaudit perms file failed.'
+ LOG_ERROR 'Check ntfssecaudit perms file failed.'
+ message='Check ntfssecaudit perms file failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ntfssecaudit perms file failed.'
Thu Dec 29 01:58:53 2022 - ERROR - Check ntfssecaudit perms file failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfssecaudit.sh line 54'
+ message='oe_test_ntfs-3g_ntfssecaudit.sh line 54'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfssecaudit.sh line 54'
Thu Dec 29 01:58:54 2022 - ERROR - oe_test_ntfs-3g_ntfssecaudit.sh line 54
+ return 0
+ ntfssecaudit -rv /dev/vdb 777 test
+ grep 'No errors were found'
"/dev/vdb" opened read-write
"/dev/vdb" closed
** 1 error was found
+ CHECK_RESULT 1 0 0 'Check ntfssecaudit perms directory failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfssecaudit perms directory failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfssecaudit perms directory failed.'
+ LOG_ERROR 'Check ntfssecaudit perms directory failed.'
+ message='Check ntfssecaudit perms directory failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ntfssecaudit perms directory failed.'
Thu Dec 29 01:58:55 2022 - ERROR - Check ntfssecaudit perms directory failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfssecaudit.sh line 56'
+ message='oe_test_ntfs-3g_ntfssecaudit.sh line 56'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfssecaudit.sh line 56'
Thu Dec 29 01:58:55 2022 - ERROR - oe_test_ntfs-3g_ntfssecaudit.sh line 56
+ return 0
+ LOG_INFO 'End of the test.'
+ message='End of the test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of the test.'
Thu Dec 29 01:58:56 2022 - INFO  - End of the test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 5
+ test 5 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Dec 29 01:58:57 2022 - ERROR - failed to execute the case.
+ exit 5
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Thu Dec 29 01:58:58 2022 - INFO  - Start to restore the test environment.
+ expect
spawn mkfs.ext4 /dev/vdb
y
mke2fs 1.46.4 (18-Aug-2021)
/dev/vdb contains a ntfs file system
Proceed anyway? (y,N) Discarding device blocks:      0/512000             done                            
Creating filesystem with 512000 1k blocks and 128016 inodes
Filesystem UUID: 71d5c72e-cdd5-4663-a11c-2d864cf15ca1
Superblock backups stored on blocks: 
	8193, 24577, 40961, 57345, 73729, 204801, 221185, 401409

Allocating group tables:  0/63     done                            
Writing inode tables:  0/63     done                            
Creating journal (8192 blocks): done
Writing superblocks and filesystem accounting information:  0/63     done

+ rm -rf /mnt/windows test.txt
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmp9cezxutv ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmp9cezxutv
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish restoring the test environment.'
+ message='Finish restoring the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish restoring the test environment.'
Thu Dec 29 01:59:10 2022 - INFO  - Finish restoring the test environment.
