+ source common/common_lib.sh
++ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Thu Dec 15 18:19:50 2022 - INFO  - Start to prepare the test environment.
+ get_disk
++ TEST_DISK
++ id=1
++ python3 /root/GitRepo/mugen-riscv/libs/locallibs/get_test_device.py --device disk --node 1
+ disks='vdb vdc vdd vde'
+ disk_list=($disks)
+ disk1=vdb
+ disk2=vdc
+ DNF_INSTALL ntfs-3g
+ pkgs=ntfs-3g
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs ntfs-3g --node 1 --tempfile ''
+ tmpfile2=/tmp/tmppsxc479i
+ '[' -z '' ']'
+ tmpfile=/tmp/tmppsxc479i
+ mkntfs --fast /dev/vdb
Cluster size has been automatically set to 4096 bytes.
Creating NTFS volume structures.
mkntfs completed successfully. Have a nice day.
+ mkntfs --fast /dev/vdc
Cluster size has been automatically set to 4096 bytes.
Creating NTFS volume structures.
mkntfs completed successfully. Have a nice day.
+ mkdir -p /mnt/windows
+ ntfs-3g /dev/vdb /mnt/windows
modprobe: FATAL: Module fuse not found in directory /lib/modules/5.10.0-9.oe2203.riscv64
ntfs-3g-mount: fuse device is missing, try 'modprobe fuse' as root
+ touch /mnt/windows/test.txt
+ rm -rf /mnt/windows/test.txt
+ umount /mnt/windows
umount: /mnt/windows: not mounted.
+ LOG_INFO 'Finish preparing the test environment.'
+ message='Finish preparing the test environment.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish preparing the test environment.'
Thu Dec 15 18:20:48 2022 - INFO  - Finish preparing the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Thu Dec 15 18:20:49 2022 - INFO  - Start to run test.
+ ntfsundelete --help
+ grep 'Usage: ntfsundelete \[options\]'
Usage: ntfsundelete [options] device
+ CHECK_RESULT 0 0 0 'Check ntfsundelete --help failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check ntfsundelete --help failed.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ ntfsundelete --version
+ grep 'ntfsundelete v'
ntfsundelete v2021.8.22 (libntfs-3g) - Recover deleted files from an NTFS Volume.
+ CHECK_RESULT 0 0 0 'Check ntfsundelete --version failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check ntfsundelete --version failed.'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep test.txt
+ ntfsundelete --scan /dev/vdb --force
+ CHECK_RESULT 1 0 0 'Check ntfsundelete --scan failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfsundelete --scan failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfsundelete --scan failed.'
+ LOG_ERROR 'Check ntfsundelete --scan failed.'
+ message='Check ntfsundelete --scan failed.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ntfsundelete --scan failed.'
Thu Dec 15 18:20:51 2022 - ERROR - Check ntfsundelete --scan failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfsundelete_01.sh line 40'
+ message='oe_test_ntfs-3g_ntfsundelete_01.sh line 40'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfsundelete_01.sh line 40'
Thu Dec 15 18:20:52 2022 - ERROR - oe_test_ntfs-3g_ntfsundelete_01.sh line 40
+ return 0
+ grep test.txt
+ ntfsundelete --percentage 10 /dev/vdb --force
+ CHECK_RESULT 1 0 0 'Check ntfsundelete --percentage failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfsundelete --percentage failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfsundelete --percentage failed.'
+ LOG_ERROR 'Check ntfsundelete --percentage failed.'
+ message='Check ntfsundelete --percentage failed.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ntfsundelete --percentage failed.'
Thu Dec 15 18:20:54 2022 - ERROR - Check ntfsundelete --percentage failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfsundelete_01.sh line 42'
+ message='oe_test_ntfs-3g_ntfsundelete_01.sh line 42'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfsundelete_01.sh line 42'
Thu Dec 15 18:20:55 2022 - ERROR - oe_test_ntfs-3g_ntfsundelete_01.sh line 42
+ return 0
+ ntfsundelete --match test.txt /dev/vdb --force
+ grep test.txt
+ CHECK_RESULT 1 0 0 'Check ntfsundelete --match failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfsundelete --match failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfsundelete --match failed.'
+ LOG_ERROR 'Check ntfsundelete --match failed.'
+ message='Check ntfsundelete --match failed.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ntfsundelete --match failed.'
Thu Dec 15 18:20:56 2022 - ERROR - Check ntfsundelete --match failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfsundelete_01.sh line 44'
+ message='oe_test_ntfs-3g_ntfsundelete_01.sh line 44'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfsundelete_01.sh line 44'
Thu Dec 15 18:20:57 2022 - ERROR - oe_test_ntfs-3g_ntfsundelete_01.sh line 44
+ return 0
+ grep test.txt
+ ntfsundelete --case --match test.txt /dev/vdb --force
+ CHECK_RESULT 1 0 0 'Check ntfsundelete --case failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfsundelete --case failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfsundelete --case failed.'
+ LOG_ERROR 'Check ntfsundelete --case failed.'
+ message='Check ntfsundelete --case failed.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ntfsundelete --case failed.'
Thu Dec 15 18:20:59 2022 - ERROR - Check ntfsundelete --case failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfsundelete_01.sh line 46'
+ message='oe_test_ntfs-3g_ntfsundelete_01.sh line 46'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfsundelete_01.sh line 46'
Thu Dec 15 18:21:00 2022 - ERROR - oe_test_ntfs-3g_ntfsundelete_01.sh line 46
+ return 0
+ ntfsundelete --size 0 /dev/vdb --force
+ grep test.txt
+ CHECK_RESULT 1 0 0 'Check ntfsundelete --size failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfsundelete --size failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfsundelete --size failed.'
+ LOG_ERROR 'Check ntfsundelete --size failed.'
+ message='Check ntfsundelete --size failed.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ntfsundelete --size failed.'
Thu Dec 15 18:21:01 2022 - ERROR - Check ntfsundelete --size failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfsundelete_01.sh line 48'
+ message='oe_test_ntfs-3g_ntfsundelete_01.sh line 48'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfsundelete_01.sh line 48'
Thu Dec 15 18:21:03 2022 - ERROR - oe_test_ntfs-3g_ntfsundelete_01.sh line 48
+ return 0
+ ntfsundelete --time 2021y /dev/vdb --force
+ grep test.txt
+ CHECK_RESULT 1 0 0 'Check ntfsundelete --time failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfsundelete --time failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfsundelete --time failed.'
+ LOG_ERROR 'Check ntfsundelete --time failed.'
+ message='Check ntfsundelete --time failed.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ntfsundelete --time failed.'
Thu Dec 15 18:21:04 2022 - ERROR - Check ntfsundelete --time failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfsundelete_01.sh line 50'
+ message='oe_test_ntfs-3g_ntfsundelete_01.sh line 50'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfsundelete_01.sh line 50'
Thu Dec 15 18:21:05 2022 - ERROR - oe_test_ntfs-3g_ntfsundelete_01.sh line 50
+ return 0
+ ntfsundelete --undelete --match test.txt /dev/vdb --force
+ grep 'Undeleted '\''test.txt'\'' successfully to test.txt'
+ CHECK_RESULT 1 0 0 'Check ntfsundelete --undelete failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfsundelete --undelete failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfsundelete --undelete failed.'
+ LOG_ERROR 'Check ntfsundelete --undelete failed.'
+ message='Check ntfsundelete --undelete failed.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ntfsundelete --undelete failed.'
Thu Dec 15 18:21:07 2022 - ERROR - Check ntfsundelete --undelete failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfsundelete_01.sh line 52'
+ message='oe_test_ntfs-3g_ntfsundelete_01.sh line 52'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfsundelete_01.sh line 52'
Thu Dec 15 18:21:08 2022 - ERROR - oe_test_ntfs-3g_ntfsundelete_01.sh line 52
+ return 0
+ ntfsundelete --inode 7 /dev/vdb --force
+ grep test.txt
+ CHECK_RESULT 1 0 0 'Check ntfsundelete --inode failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check ntfsundelete --inode failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check ntfsundelete --inode failed.'
+ LOG_ERROR 'Check ntfsundelete --inode failed.'
+ message='Check ntfsundelete --inode failed.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check ntfsundelete --inode failed.'
Thu Dec 15 18:21:09 2022 - ERROR - Check ntfsundelete --inode failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_ntfsundelete_01.sh line 54'
+ message='oe_test_ntfs-3g_ntfsundelete_01.sh line 54'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_ntfsundelete_01.sh line 54'
Thu Dec 15 18:21:10 2022 - ERROR - oe_test_ntfs-3g_ntfsundelete_01.sh line 54
+ return 0
+ LOG_INFO 'End of the test.'
+ message='End of the test.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of the test.'
Thu Dec 15 18:21:11 2022 - INFO  - End of the test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 8
+ test 8 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Dec 15 18:21:13 2022 - ERROR - failed to execute the case.
+ exit 8
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Thu Dec 15 18:21:14 2022 - INFO  - Start to restore the test environment.
+ expect
spawn mkfs.ext4 /dev/vdb
y
mke2fs 1.46.4 (18-Aug-2021)
/dev/vdb contains a ntfs file system
Proceed anyway? (y,N) Discarding device blocks:      0/512000             done                            
Creating filesystem with 512000 1k blocks and 128016 inodes
Filesystem UUID: 0b3889ac-cc48-4409-9346-63ac3d5b95ee
Superblock backups stored on blocks: 
	8193, 24577, 40961, 57345, 73729, 204801, 221185, 401409

Allocating group tables:  0/63     done                            
Writing inode tables:  0/63     done                            
Creating journal (8192 blocks): done
Writing superblocks and filesystem accounting information:  0/63     done

+ rm -rf /mnt/windows 'test.txt*'
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmppsxc479i ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmppsxc479i
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish restoring the test environment.'
+ message='Finish restoring the test environment.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish restoring the test environment.'
Thu Dec 15 18:21:38 2022 - INFO  - Finish restoring the test environment.
