[stdlog] 2022-10-28 21:02:33,939 avocado.test INFO | INIT 1-tests/system_base/util-linux/tc_ag_util-linux_mkfs_fun_002.py:Test.test
[stdlog] 2022-10-28 21:02:33,940 avocado.test DEBUG| PARAMS (key=timeout, path=*, default=None) => None
[stdlog] 2022-10-28 21:02:33,940 avocado.test DEBUG| Test metadata:
[stdlog] 2022-10-28 21:02:33,940 avocado.test DEBUG|   filename: /root/GitRepo/anolis-pkg-tests/tests/system_base/util-linux/tc_ag_util-linux_mkfs_fun_002.py
[stdlog] 2022-10-28 21:02:33,940 avocado.test DEBUG|   teststmpdir: /var/tmp/avocado_cmoau920
[stdlog] 2022-10-28 21:02:33,940 avocado.test INFO | START 1-tests/system_base/util-linux/tc_ag_util-linux_mkfs_fun_002.py:Test.test
[stdlog] 2022-10-28 21:02:33,940 avocado.test INFO | setup
[stdlog] 2022-10-28 21:02:33,941 avocado.test DEBUG| PARAMS (key=remote, path=*, default=None) => None
[stdlog] 2022-10-28 21:02:33,941 avocado.utils.process INFO | Running 'rpm -q util-linux'
[stdlog] 2022-10-28 21:02:33,949 avocado.utils.process DEBUG| [stdout] util-linux-2.32.1-35.0.1.an8.x86_64
[stdlog] 2022-10-28 21:02:33,950 avocado.utils.process INFO | Command 'rpm -q util-linux' finished with 0 after 0.008136889s
[stdlog] 2022-10-28 21:02:33,950 avocado.utils.process INFO | Running 'yum update util-linux -y'
[stdlog] 2022-10-28 21:02:34,232 avocado.utils.process DEBUG| [stdout] Last metadata expiration check: 2:45:02 ago on Fri 28 Oct 2022 06:17:32 PM CST.
[stdlog] 2022-10-28 21:02:34,509 avocado.utils.process DEBUG| [stdout] Dependencies resolved.
[stdlog] 2022-10-28 21:02:34,510 avocado.utils.process DEBUG| [stdout] Nothing to do.
[stdlog] 2022-10-28 21:02:34,510 avocado.utils.process DEBUG| [stdout] Complete!
[stdlog] 2022-10-28 21:02:34,834 avocado.utils.process INFO | Command 'yum update util-linux -y' finished with 0 after 0.883710468s
[stdlog] 2022-10-28 21:02:34,835 avocado.utils.process INFO | Running 'mkfs -t {{ext4}} {{path/to/partition}}'
[stdlog] 2022-10-28 21:02:34,837 avocado.utils.process INFO | Command 'mkfs -t {{ext4}} {{path/to/partition}}' finished with 1 after 0.001405056s
[stdlog] 2022-10-28 21:02:34,837 avocado.utils.process DEBUG| [stderr] mkfs: failed to execute mkfs.{{ext4}}: No such file or directory
[stdlog] 2022-10-28 21:02:34,838 avocado.test ERROR| 
[stdlog] 2022-10-28 21:02:34,838 avocado.test ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:761
[stdlog] 2022-10-28 21:02:34,838 avocado.test ERROR| Traceback (most recent call last):
[stdlog] 2022-10-28 21:02:34,838 avocado.test ERROR|   File "/root/GitRepo/anolis-pkg-tests/tests/system_base/util-linux/tc_ag_util-linux_mkfs_fun_002.py", line 27, in test
[stdlog] 2022-10-28 21:02:34,838 avocado.test ERROR|     ret_c, ret_o = self.cmd("mkfs -t {{ext4}} {{path/to/partition}}")
[stdlog] 2022-10-28 21:02:34,838 avocado.test ERROR|   File "/root/GitRepo/anolis-pkg-tests/tests/common/basetest.py", line 54, in cmd
[stdlog] 2022-10-28 21:02:34,838 avocado.test ERROR|     return self.local.cmd(command, ignore_status=ignore_status)
[stdlog] 2022-10-28 21:02:34,838 avocado.test ERROR|   File "/root/GitRepo/anolis-pkg-tests/tests/common/hosts.py", line 45, in cmd
[stdlog] 2022-10-28 21:02:34,839 avocado.test ERROR|     result = process.run(command, ignore_status=ignore_status, shell=True)
[stdlog] 2022-10-28 21:02:34,839 avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1015, in run
[stdlog] 2022-10-28 21:02:34,839 avocado.test ERROR|     raise CmdError(cmd, sp.result)
[stdlog] 2022-10-28 21:02:34,839 avocado.test ERROR| avocado.utils.process.CmdError: Command 'mkfs -t {{ext4}} {{path/to/partition}}' failed.
[stdlog] 2022-10-28 21:02:34,839 avocado.test ERROR| stdout: b''
[stdlog] 2022-10-28 21:02:34,839 avocado.test ERROR| stderr: b'mkfs: failed to execute mkfs.{{ext4}}: No such file or directory\n'
[stdlog] 2022-10-28 21:02:34,839 avocado.test ERROR| additional_info: None
[stdlog] 2022-10-28 21:02:34,839 avocado.test ERROR| 
[stdlog] 2022-10-28 21:02:34,839 avocado.test DEBUG| Local variables:
[stdlog] 2022-10-28 21:02:34,851 avocado.test DEBUG|  -> self <class 'tc_ag_util-linux_mkfs_fun_002.Test'>: 1-tests/system_base/util-linux/tc_ag_util-linux_mkfs_fun_002.py:Test.test
[stdlog] 2022-10-28 21:02:34,851 avocado.test INFO | teardown
[stdlog] 2022-10-28 21:02:34,851 avocado.utils.process INFO | Running 'yum erase  -y'
[stdlog] 2022-10-28 21:02:35,132 avocado.utils.process DEBUG| [stderr] No packages marked for removal.
[stdlog] 2022-10-28 21:02:35,139 avocado.utils.process DEBUG| [stdout] Dependencies resolved.
[stdlog] 2022-10-28 21:02:35,140 avocado.utils.process DEBUG| [stdout] Nothing to do.
[stdlog] 2022-10-28 21:02:35,140 avocado.utils.process DEBUG| [stdout] Complete!
[stdlog] 2022-10-28 21:02:35,484 avocado.utils.process INFO | Command 'yum erase  -y' finished with 0 after 0.631892758s
[stdlog] 2022-10-28 21:02:35,484 avocado.test ERROR| Traceback (most recent call last):
[stdlog] 2022-10-28 21:02:35,484 avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 796, in _run_avocado
[stdlog]     raise test_exception
[stdlog] 2022-10-28 21:02:35,485 avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 756, in _run_avocado
[stdlog]     testMethod()
[stdlog] 2022-10-28 21:02:35,485 avocado.test ERROR|   File "/root/GitRepo/anolis-pkg-tests/tests/system_base/util-linux/tc_ag_util-linux_mkfs_fun_002.py", line 27, in test
[stdlog]     ret_c, ret_o = self.cmd("mkfs -t {{ext4}} {{path/to/partition}}")
[stdlog] 2022-10-28 21:02:35,485 avocado.test ERROR|   File "/root/GitRepo/anolis-pkg-tests/tests/common/basetest.py", line 54, in cmd
[stdlog]     return self.local.cmd(command, ignore_status=ignore_status)
[stdlog] 2022-10-28 21:02:35,485 avocado.test ERROR|   File "/root/GitRepo/anolis-pkg-tests/tests/common/hosts.py", line 45, in cmd
[stdlog]     result = process.run(command, ignore_status=ignore_status, shell=True)
[stdlog] 2022-10-28 21:02:35,485 avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1015, in run
[stdlog]     raise CmdError(cmd, sp.result)
[stdlog] 2022-10-28 21:02:35,485 avocado.test ERROR| avocado.utils.process.CmdError: Command 'mkfs -t {{ext4}} {{path/to/partition}}' failed.
[stdlog] stdout: b''
[stdlog] stderr: b'mkfs: failed to execute mkfs.{{ext4}}: No such file or directory\n'
[stdlog] additional_info: None
[stdlog] 2022-10-28 21:02:35,485 avocado.test ERROR| ERROR 1-tests/system_base/util-linux/tc_ag_util-linux_mkfs_fun_002.py:Test.test -> CmdError: Command 'mkfs -t {{ext4}} {{path/to/partition}}' failed.
[stdlog] stdout: b''
[stdlog] stderr: b'mkfs: failed to execute mkfs.{{ext4}}: No such file or directory\n'
[stdlog] additional_info: None
[stdlog] 2022-10-28 21:02:35,485 avocado.test INFO | 
