+ source ../common/common_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Tue Dec  6 08:30:34 2022 - INFO  - Start environmental preparation.
+ DNF_INSTALL abrt-addon-vmcore
+ pkgs=abrt-addon-vmcore
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs abrt-addon-vmcore --node 1 --tempfile ''
+ tmpfile2='Error: 
 Problem: conflicting requests
  - nothing provides kexec-tools needed by abrt-addon-vmcore-2.15.0-3.an8.riscv64'
+ '[' -z '' ']'
+ tmpfile='Error: 
 Problem: conflicting requests
  - nothing provides kexec-tools needed by abrt-addon-vmcore-2.15.0-3.an8.riscv64'
+ systemctl start abrtd.service
Warning: The unit file, source configuration file or drop-ins of abrtd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
A dependency job for abrtd.service failed. See 'journalctl -xe' for details.
+ touch /var/crash/test
touch: cannot touch '/var/crash/test': No such file or directory
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Tue Dec  6 08:31:05 2022 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Tue Dec  6 08:31:05 2022 - INFO  - Start testing...
+ test_execution abrt-vmcore.service
+ service=abrt-vmcore.service
++ date '+%Y-%m-%d %T'
+ log_time='2022-12-06 08:31:05'
+ test_restart abrt-vmcore.service
+ service=abrt-vmcore.service
+ systemctl restart abrt-vmcore.service
Failed to restart abrt-vmcore.service: Unit abrt-vmcore.service not found.
+ CHECK_RESULT 5 0 0 'abrt-vmcore.service restart failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='abrt-vmcore.service restart failed'
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'abrt-vmcore.service restart failed'
+ LOG_ERROR 'abrt-vmcore.service restart failed'
+ message='abrt-vmcore.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'abrt-vmcore.service restart failed'
Tue Dec  6 08:31:06 2022 - ERROR - abrt-vmcore.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Tue Dec  6 08:31:07 2022 - ERROR - ../common/common_lib.sh line 34
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ grep 'Active: active'
+ systemctl status abrt-vmcore.service
Unit abrt-vmcore.service could not be found.
+ CHECK_RESULT 1 0 0 'abrt-vmcore.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='abrt-vmcore.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'abrt-vmcore.service restart failed'
+ LOG_ERROR 'abrt-vmcore.service restart failed'
+ message='abrt-vmcore.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'abrt-vmcore.service restart failed'
Tue Dec  6 08:31:13 2022 - ERROR - abrt-vmcore.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Tue Dec  6 08:31:14 2022 - ERROR - ../common/common_lib.sh line 37
+ return 0
+ systemctl stop abrt-vmcore.service
Failed to stop abrt-vmcore.service: Unit abrt-vmcore.service not loaded.
+ CHECK_RESULT 5 0 0 'abrt-vmcore.service stop failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='abrt-vmcore.service stop failed'
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'abrt-vmcore.service stop failed'
+ LOG_ERROR 'abrt-vmcore.service stop failed'
+ message='abrt-vmcore.service stop failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'abrt-vmcore.service stop failed'
Tue Dec  6 08:31:15 2022 - ERROR - abrt-vmcore.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 39'
+ message='../common/common_lib.sh line 39'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 39'
Tue Dec  6 08:31:15 2022 - ERROR - ../common/common_lib.sh line 39
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ grep 'Active: inactive'
+ systemctl status abrt-vmcore.service
Unit abrt-vmcore.service could not be found.
+ CHECK_RESULT 1 0 0 'abrt-vmcore.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='abrt-vmcore.service stop failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'abrt-vmcore.service stop failed'
+ LOG_ERROR 'abrt-vmcore.service stop failed'
+ message='abrt-vmcore.service stop failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'abrt-vmcore.service stop failed'
Tue Dec  6 08:31:22 2022 - ERROR - abrt-vmcore.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Tue Dec  6 08:31:23 2022 - ERROR - ../common/common_lib.sh line 42
+ return 0
+ systemctl start abrt-vmcore.service
Failed to start abrt-vmcore.service: Unit abrt-vmcore.service not found.
+ CHECK_RESULT 5 0 0 'abrt-vmcore.service start failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='abrt-vmcore.service start failed'
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'abrt-vmcore.service start failed'
+ LOG_ERROR 'abrt-vmcore.service start failed'
+ message='abrt-vmcore.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'abrt-vmcore.service start failed'
Tue Dec  6 08:31:23 2022 - ERROR - abrt-vmcore.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Tue Dec  6 08:31:24 2022 - ERROR - ../common/common_lib.sh line 44
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status abrt-vmcore.service
+ grep 'Active: active'
Unit abrt-vmcore.service could not be found.
+ CHECK_RESULT 1 0 0 'abrt-vmcore.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='abrt-vmcore.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'abrt-vmcore.service start failed'
+ LOG_ERROR 'abrt-vmcore.service start failed'
+ message='abrt-vmcore.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'abrt-vmcore.service start failed'
Tue Dec  6 08:31:30 2022 - ERROR - abrt-vmcore.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Tue Dec  6 08:31:31 2022 - ERROR - ../common/common_lib.sh line 47
+ return 0
+ test_enabled abrt-vmcore.service
+ service=abrt-vmcore.service
++ systemctl is-enabled abrt-vmcore.service
Failed to get unit file state for abrt-vmcore.service: No such file or directory
+ state=
+ '[' '' == enabled ']'
+ '[' '' == disabled ']'
+ '[' '' == masked ']'
+ '[' '' == static ']'
+ LOG_INFO 'Unit is indirect, ignoring.'
+ message='Unit is indirect, ignoring.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Unit is indirect, ignoring.'
Tue Dec  6 08:31:32 2022 - INFO  - Unit is indirect, ignoring.
+ journalctl --since '2022-12-06 08:31:05' -u abrt-vmcore.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
+ CHECK_RESULT 1 0 1 'There is an error message for the log of abrt-vmcore.service'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of abrt-vmcore.service'
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ test_reload abrt-vmcore.service
+ service=abrt-vmcore.service
+ systemctl start abrt-vmcore.service
Failed to start abrt-vmcore.service: Unit abrt-vmcore.service not found.
+ systemctl reload abrt-vmcore.service
+ grep 'Job type reload is not applicable'
+ CHECK_RESULT 1 0 0 'Job type reload is not applicable for unit abrt-vmcore.service'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Job type reload is not applicable for unit abrt-vmcore.service'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Job type reload is not applicable for unit abrt-vmcore.service'
+ LOG_ERROR 'Job type reload is not applicable for unit abrt-vmcore.service'
+ message='Job type reload is not applicable for unit abrt-vmcore.service'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Job type reload is not applicable for unit abrt-vmcore.service'
Tue Dec  6 08:31:33 2022 - ERROR - Job type reload is not applicable for unit abrt-vmcore.service
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 91'
+ message='../common/common_lib.sh line 91'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 91'
Tue Dec  6 08:31:34 2022 - ERROR - ../common/common_lib.sh line 91
+ return 0
+ systemctl status abrt-vmcore.service
+ grep 'Active: active'
Unit abrt-vmcore.service could not be found.
+ grep 'inactive (dead)'
+ systemctl status abrt-vmcore.service
Unit abrt-vmcore.service could not be found.
+ return 1
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Tue Dec  6 08:31:35 2022 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 7
+ test 7 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Dec  6 08:31:35 2022 - ERROR - failed to execute the case.
+ exit 7
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Tue Dec  6 08:31:36 2022 - INFO  - start environment cleanup.
+ systemctl stop abrt-vmcore.service
Failed to stop abrt-vmcore.service: Unit abrt-vmcore.service not loaded.
+ systemctl stop abrtd.service
Warning: The unit file, source configuration file or drop-ins of abrtd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
+ rm -rf /var/crash/test
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z Error: 
 Problem: conflicting requests
  - nothing provides kexec-tools needed by abrt-addon-vmcore-2.15.0-3.an8.riscv64 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile 'Error: 
 Problem: conflicting requests
  - nothing provides kexec-tools needed by abrt-addon-vmcore-2.15.0-3.an8.riscv64'
Traceback (most recent call last):
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 181, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 152, in rpm_remove
    with open(tmpfile, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Error: \n Problem: conflicting requests\n  - nothing provides kexec-tools needed by abrt-addon-vmcore-2.15.0-3.an8.riscv64'
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Tue Dec  6 08:31:42 2022 - INFO  - Finish environment cleanup!
